name: Mock Digest Preview

on:
  workflow_dispatch:

jobs:
  mock-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Send mock digest email
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_FROM_EMAIL: ${{ secrets.BREVO_FROM_EMAIL }}
          BREVO_FROM_NAME: ${{ secrets.BREVO_FROM_NAME }}
          BREVO_TO: ${{ secrets.BREVO_TO }}
        run: node scripts/digest-mock.js
