name: Digest Mock

on:
  workflow_dispatch:

jobs:
  run-mock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run mock digest
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_FROM_EMAIL: ${{ secrets.BREVO_FROM_EMAIL }}
          BREVO_FROM_NAME: ${{ secrets.BREVO_FROM_NAME }}
          BREVO_TO: ${{ secrets.BREVO_TO }}
        run: node scripts/digest-mock.js

      - name: Upload mock digest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mock-digest
          path: |
            data/digest/**
          if-no-files-found: error
