name: Digest Mock

on:
  workflow_dispatch:

jobs:
  run-digest-mock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run digest mock
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_FROM_EMAIL: ${{ secrets.BREVO_FROM_EMAIL }}
          BREVO_FROM_NAME: ${{ secrets.BREVO_FROM_NAME }}
          BREVO_TO: ${{ secrets.BREVO_TO }}
        run: node scripts/digest-mock.js

      - name: Upload digest artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: digest-mock
          path: |
            data/digest/**
          if-no-files-found: ignore
