name: pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # daily 6am UTC

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json ~/.npm
          npm install

      - name: Refresh Raindrop token (non-blocking)
        run: node scripts/refresh-raindrop.js || true
        env:
          RAINDROP_CLIENT_ID: ${{ secrets.RAINDROP_CLIENT_ID }}
          RAINDROP_CLIENT_SECRET: ${{ secrets.RAINDROP_CLIENT_SECRET }}
          RAINDROP_REFRESH_TOKEN: ${{ secrets.RAINDROP_REFRESH_TOKEN }}
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

      - name: Debug GEMINI_API secret
        run: |
          if [ -z "$GEMINI_API" ]; then
            echo "DEBUG: GEMINI_API is missing or empty"
          else
            echo "DEBUG: GEMINI_API is set, length=${#GEMINI_API}"
            echo "DEBUG: GEMINI_API starts with ${GEMINI_API:0:3}..."
          fi
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}

      - name: Run pipeline
        run: node scripts/run-pipeline.js
        env:
          # Existing secrets
          KNOWLEDGEBASE_TOKEN: ${{ secrets.KNOWLEDGEBASE_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_FROM_EMAIL: ${{ secrets.BREVO_FROM_EMAIL }}
          BREVO_FROM_NAME: ${{ secrets.BREVO_FROM_NAME }}
          BREVO_TO: ${{ secrets.BREVO_TO }}
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

          # New AI provider keys (aligned with code)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API: ${{ secrets.GEMINI_API }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

          # Hard caps (for guardrails.js)
          MAX_OPENAI_CALLS_PER_RUN: ${{ secrets.MAX_OPENAI_CALLS_PER_RUN }}
          MAX_GEMINI_CALLS_PER_RUN: ${{ secrets.MAX_GEMINI_CALLS_PER_RUN }}
          MAX_DEEPSEEK_SPEND: ${{ secrets.MAX_DEEPSEEK_SPEND }}
          MAX_OPENROUTER_SPEND: ${{ secrets.MAX_OPENROUTER_SPEND }}

      - name: Upload pipeline artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: |
            data/cache/**
            data/curated/**
            data/digest/**
            data/publish/**
            data/knowledge.json
