name: Orchestrate Knowledgebase

on:
  workflow_dispatch:
  schedule:
    # 11:00 PM (previous day) Waterloo time ≈ 03:00 UTC
    - cron: "0 3 * * *"
    # 09:00 AM Waterloo time ≈ 13:00 UTC
    - cron: "0 13 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Execute pipeline
        env:
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          KNOWLEDGEBASE_TOKEN: ${{ secrets.KNOWLEDGEBASE_TOKEN }}
        run: npm run pipeline

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: logs/
          if-no-files-found: ignore

