name: Reset Orchestration Cache

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run reset-cache script
        run: node scripts/reset-cache.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/cache
          git commit -m "Reset orchestration cache" || echo "No changes to commit"
          git push
